
server.port=8082
spring.application.name=kafkaConsumerPlayground

#Kafka available brokers
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093

#Consumer group
spring.kafka.consumer.group-id=order-consumer-group

#Use wrapper
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

#Wrapper above actual class
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.event_driven_architecture.kafkaConsumerPlayground.Consumer.Model.Order
#spring.kafka.consumer.properties.spring.json.type.mapping=com.eda.kafkaPlayGround.Producer.Model.Order:com.event_driven_architecture.kafkaConsumerPlayground.Consumer.Model.Order,com.eda.kafkaPlayGround.Producer.Model.Payment:com.event_driven_architecture.kafkaConsumerPlayground.Consumer.Model.Payment
spring.kafka.consumer.properties.spring.json.use.type.headers=false